### ISSUE TITLE
Create ShelterPartner logo

### ISSUE THREAD

**Issue by JaredDanielJones** [Some-Apps/PawPartner#88]
Here's the idea but am not at all attached to it. Also I made it in an app I can't export from or use the vectors from. I wish there were "a"s in it because I liked the pawprints as the "a" better

Light Orange Hex: #EBCA96
Light Blue Hex: #89CFF0
![IMG_F3B8FB42150E-1](https://github.com/user-attachments/assets/77043320-710e-4d7c-8a22-e1ef5f9dffb8)

**Comment by rhjones777** [comment]
Great start. I'd really like to work on this to come up with some options Jared. Can you assign it to me?

**Comment by JaredDanielJones** [comment]
@all-contributors please add @rhjones777  for design
